AppReceitas/urls.py
from django.urls import path
from . import views

app_name = 'receitas'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/<int:id>/', views.recipe, name='receita'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/category/<int:category_id>/', views.category, name='category'),
    path('recipe/<int:id>/', views.recipe, name='recipe'),
]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=200)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/cover/%Y/%m/%d/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.title

recipe/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.recipes.factory import make_recipe
from .models import Recipe

# Create your views here.

def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipe/pages/home.html', context={'recipes': recipes})

def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(category__id=category_id, 
                                                    is_published=True)
                                                    .order_by('-id'))
    
    return render(request, 'recipe/pages/category.html',
                  context={'recipes': recipes, 
                            'title': f'{recipes[0].category.name} - Category |'})

def recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id, is_published=True)
    
    return render(request, 'recipe/pages/recipe-view.html',
                  context={'recipe': recipe,
                           'is_detail_page': True,
                           })

AppReceitas/templates/recipe/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
    
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'recipe/partials/receitas.html' %}
    {% endfor %}
</div>

{% endblock content %}

AppReceitas/templates/recipe/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} Alterar | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipe/partials/receitas.html' %}
</div>
{% endblock content %}

AppReceitas/templates/recipe/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'receitas:home' %}">
                <i class="far fa-drumstick-bite main-logo-icon"></i>
                <span class="main-logo-text">Receitas</span>
            </a>
        </h1>
    </div>
</header> 

AppReceitas/templates/recipe/partials/receitas.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'receitas:receita' recipe.id %}">
        <img src="{{ recipe.cover.url }}" alt="temporario">
        </a>
    </div>

    <!-- titulo do texto -->
    <div class="recipe-title-container">
        
        <h2 class="recipe-title">
            <a href="{% url 'receitas:receita' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

        <!-- segunda linha de texto -->
        <div class="recipe-author">
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            </span>
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
            </span>
            <span class="recipe-author-item">
                <a href="#">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        </div>
            <!-- Terceira linha do texto -->
            <div class="recipe-content">
                <p>{{ recipe.description}}</p>
            </div>

                <!-- Quarta linha do texto -->
                <div class="recipe-meta-container">
                    <div class="recipe-meta recipe-preparation">
                        <h3 class="recipe-meta-title">
                            <i class="fas fa-stopwatch"></i>
                            Preparo
                        </h3>
                        <div class="recipe-meta-text">
                            {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                        </div>
                    </div>    
                        <div class="recipe-meta recipe-servings">
                            <h3 class="recipe-meta-title">
                                <i class="fas fa-pizza-slice"></i>
                                Porções
                            </h3>
                            <div class="recipe-meta-text">
                                {{ recipe.servings }} {{recipe.servings_unit}}
                            </div>
                        </div>  
                </div>

                {% if is_detail_page is not True %}
                    <!-- botão -->
                    <footer class="recipe-footer">
                        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'receitas:receita' recipe.id %}">
                        <i class="fas fa-eye"></i>
                        <span>ver mais...</span>
                        </a>
                    </footer>
                {% endif %}

                <!-- sem botão para aparecer descrições da receita -->
                
                {% if is_detail_page %}
                    
                    <div class="preparation-steps">
                        {{ recipe.preparation_steps|linebreaksbr }}
                    </div>

                {% endif %}
                    
</div>

recipe/templates/recipe/pages/category.html
{% extends 'global/base.html' %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
    
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'recipe/partials/recipe.html' %}
    {% endfor %}
</div>

{% endblock content %}

recipe/templates/recipe/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
    
<div class="main-content main-content-list container">

{% for recipe in recipes %}
    {% include 'recipe/partials/recipe.html' %}
{% empty %}
    <div class="center m-y">
    <h1>No recipes found here</h1>
    </div>
{% endfor %}
</div>

{% endblock content %}

recipe/templates/recipe/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} {{recipe.title}}  | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipe/partials/recipe.html' %}
</div>
{% endblock content %}

recipe/templates/recipe/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="#">Edith Carollaine V.V Sêca</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/">Django</a>
    </div>
</footer>

recipe/templates/recipe/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css" integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css" integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css" integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'recipe/css/styles.css' %}">

recipe/templates/recipe/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="far fa-drumstick-bite main-logo-icon"></i>
                <span class="main-logo-text">Receitas</span>
            </a>
        </h1>
    </div>
</header> 

recipe/templates/recipe/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{ recipe.cover.url }}" alt="temporario">
        </a>
    </div>

    <!-- titulo do texto -->
    <div class="recipe-title-container">
        
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

        <!-- segunda linha de texto -->
        <div class="recipe-author">


            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author is not None %}
                    {% if recipe.author.first_name %}
                        {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                    {% else %}
                        {{ recipe.author.username }}
                    {% endif %}
                {% else %}
                    Desconhecido
                {% endif %}
            </span>
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
            </span>
            {% if  recipe.category is not None %}
                <span class="recipe-author-item">
                    <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                    </a>
                </span>
            {% endif %}
        </div>
            <!-- Terceira linha do texto -->
            <div class="recipe-content">
                <p>{{ recipe.description}}</p>
            </div>

                <!-- Quarta linha do texto -->
                <div class="recipe-meta-container">
                    <div class="recipe-meta recipe-preparation">
                        <h3 class="recipe-meta-title">
                            <i class="fas fa-stopwatch"></i>
                            Preparo
                        </h3>
                        <div class="recipe-meta-text">
                            {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                        </div>
                    </div>    
                        <div class="recipe-meta recipe-servings">
                            <h3 class="recipe-meta-title">
                                <i class="fas fa-pizza-slice"></i>
                                Porções
                            </h3>
                            <div class="recipe-meta-text">
                                {{ recipe.servings }} {{recipe.servings_unit}}
                            </div>
                        </div>  
                </div>

                {% if is_detail_page is not True %}
                    <!-- botão -->
                    <footer class="recipe-footer">
                        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                        <i class="fas fa-eye"></i>
                        <span>ver mais...</span>
                        </a>
                    </footer>
                {% endif %}

                <!-- sem botão para aparecer descrições da receita -->
                
                {% if is_detail_page is True %}
                    <div class="preparation-steps">
                        {% if recipe.preparation_steps_is_html is True %}
                            {{ recipe.preparation_steps|safe }}
                        {% else %}
                            {{ recipe.preparation_steps|linebreaksbr }}
                        {% endif %}
                    </div>
                {% endif %}
                    
</div>

recipe/templates/recipe/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>